CREATE DATABASE sgn_boys_db;
CREATE TABLE admission_forms (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    form_no VARCHAR(50),
    admission_year VARCHAR(10),
    roll_no VARCHAR(50),
    id_card_no VARCHAR(50),
    religion VARCHAR(50),
    category VARCHAR(50),
    stream VARCHAR(50),
    course VARCHAR(100),
    medium VARCHAR(20),
    scholar_no VARCHAR(50),
    enrollment_no VARCHAR(50),
    gender VARCHAR(20),
    dob DATE,
    candidate_name VARCHAR(200),
    father_name VARCHAR(200),
    father_occupation VARCHAR(100),
    mother_name VARCHAR(200),
    mother_occupation VARCHAR(100),
    permanent_address TEXT,
    correspondence_address TEXT,
    whatsapp VARCHAR(20),
    mobile VARCHAR(20),
    parents_mobile VARCHAR(20),
    last_institution VARCHAR(200),
    pay_ss VARCHAR(255),
    exam_name VARCHAR(100),
    exam_year VARCHAR(10),
    exam_sem VARCHAR(10),
    exam_board VARCHAR(100),
    exam_percentage VARCHAR(20),
    exam_compulsory VARCHAR(100),
    exam_optional VARCHAR(100),
    ug_optional1 VARCHAR(100),
    ug_optional2 VARCHAR(100),
    ug_optional3 VARCHAR(100),
    ug_optional4 VARCHAR(100),
    ug_optional5 VARCHAR(100),
    ug_optional6 VARCHAR(100),
    pg_optional1 VARCHAR(100),
    pg_optional2 VARCHAR(100),
    pg_optional3 VARCHAR(100),
    pg_optional4 VARCHAR(100),
    pg_optional5 VARCHAR(100),
    pg_optional6 VARCHAR(100),
    interests VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
